### ISSUE TITLE
Not using SQLAlchemy

### ISSUE THREAD

**Issue by Fuyukai** [kamilion/kaizen#1]
<SunDwarf> Kamilion, no, you will use sqlalchemy

**Comment by kamilion** [comment]
Sure, submit a pull request to sqlalchemy supporting rethinkdb.

**Comment by Omeryl** [comment]
Lol what.

**Comment by Fuyukai** [comment]
RethinkDB sucks

**Comment by kamilion** [comment]
I'll pass on your comments to the rethinkdb team.

**Comment by Fuyukai** [comment]
I don't remember the context for this but I feel vindicated

**Comment by Omeryl** [comment]
@fuyukai if you want it different, submit the patch set ;).

**Comment by kamilion** [comment]
You can feel vindicated all you wish, won't change four years of uptime though.

**Comment by Fuyukai** [comment]
I feel vindicated because rethinkdb died

**Comment by Omeryl** [comment]
@fuyukai it didn’t though, so your vindication is invalid lol.
